### ISSUE TITLE
Error when trying to reset password

### ISSUE THREAD

**Issue by gael-seroul** [3dem/emhub#107]
Hi,
I am testing the docker installation using current image Version: 1.0.2. I was able to connect using admin/admin, to insert new user using emhub.client and a small python script.
The issue is that from the logon screen if I click on _Forgot password?_  link I get this error:
**Missing content function for 'user_reset_password'** 

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/emhub/__init__.py", line 347, in get_content
    kwargs = app.dc.get(**content_kwargs)
  File "/usr/local/lib/python3.8/site-packages/emhub/data/content/dc_base.py", line 71, in get
    raise Exception(f"Missing content function for '{content_id}'")
Exception: Missing content function for 'user_reset_password'

**Comment by delarosatrevin** [comment]
Hi, thanks a lot for reporting this. There was a missing function that I brought back now, and the reset password page is now working. Anyway, this feature requires to configure a Mail server to send user the reset password token URL that they need to use. If the Mail server is not configured, I'm generating a more descriptive error message in that page. I make these fixes in the devel branch and I will close this issue now.
