### ISSUE TITLE
How setup docker installation

### ISSUE THREAD

**Issue by gael-seroul** [3dem/emhub#108]
Hi,
I am testing the docker installation. How do you setup smtp config to send emails ?  How to test it from the emhub web interface ?
Thanks

**Comment by delarosatrevin** [comment]
The following are the variables required to configure the Flask mail plugin:

```
MAIL_SERVER = "smtp.emhub.org"
MAIL_PORT = 587
MAIL_USE_TLS = 1
MAIL_DEFAULT_SENDER = "noreply@emhub.org"
```

You will need help from your institute IT regarding the mail server. For debugging purposes, you can use a dummy server available in Python (version < 3.12). Run from another terminal:

```
python -m smtpd -n -c DebuggingServer localhost:2500
```

This will run a dummy server that will print any email and not send anything. You can test using the "Reset Password" that will send an email with the reset token. The variables in the config.py for this testing server should be:

```
MAIL_SERVER = "localhost"
MAIL_PORT = 2500
MAIL_USE_TLS = 0
MAIL_DEFAULT_SENDER = "noreply@emhub.org"

```
