### ISSUE TITLE
Inserting data using python => choose instance

### ISSUE THREAD

**Issue by gael-seroul** [3dem/emhub#112]
Hi,
I have 2 instances running:

- main branch with instance in /xxx/emhub-data/
- devel branch with instance in /xxx/emhub-data-dev/

I am using:
export FLASK_APP=emhub
export EMHUB_INSTANCE=/xxx/emhub-data-dev/
python insert_user.py  => the new user is inserted in main instance
where do I setup instance target to use with python script ?
Thanks

**Comment by delarosatrevin** [comment]
If you run the command emh-client it will show you the variable to need to specify for the client to connect to a EMhub server.

```
L230184:emhub jdela80$ emh-client

export EMHUB_SERVER_URL=http://127.0.0.1:5000
export EMHUB_PASSWORD=admin
export EMHUB_INSTANCE=/Users/jdela80/.emhub/instances/test
export EMHUB_SOURCE=None
export EMHUB_TESTDATA=/Users/jdela80/work/development/emhub/testdata
export EMHUB_USER=admin
```

The really needed ones for the client are server URL, user and password.

**Comment by gael-seroul** [comment]
Hi Jose,
This is working fine thank you, you can close this issue.
